FROM python:3.11-slim


WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


COPY api ./api
COPY artifacts ./artifacts
COPY .env.example ./.env.example


ENV MODEL_PATH=artifacts/model.pkl
EXPOSE 8000


CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]