name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: python -m pyflakes api || true
      - name: Build Docker image
        run: docker build -t ml-service:$(git rev-parse --short HEAD) -f docker/Dockerfile .